// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(grunt) {
    var _this = this;
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      watch: {
        options: {
          livereload: true
        },
        script: {
          files: ["src/*.coffee"],
          tasks: ['default']
        }
      },
      copy: {
        main: {
          files: [
            {
              expand: true,
              cwd: "dist/",
              src: "*",
              dest: "../constructor/static/js/sop/"
            }
          ]
        }
      },
      coffee: {
        compile: {
          options: {
            sourceMap: true,
            join: true
          },
          files: {
            "dist/constructor.js": ["src/main.coffee", "src/builder.coffee", "src/utils.coffee", "src/geometry.coffee", "src/admin.coffee"],
            "dist/displayer.js": ["src/main.coffee", "src/builder.coffee", "src/utils.coffee", "src/geometry.coffee"]
          }
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.registerTask('default', ['coffee', 'copy']);
    grunt.registerTask('compile', ['coffee']);
    return grunt.event.on('watch', function(action, filepath) {
      return grunt.config(['jshint', 'all'], filepath);
    });
  };

}).call(this);
